- team/chris.md
> cb - created chris.md

- team/rowan.md
Added the rowan.md file as described.
> rt - Add personal rowan.md file

- team/justin.md
Add my introduction and my project ideas
> jv - add team/justin.md

- team/NORMS.md
> cb - created NORMS.md

- team/problem_scenario.md
Add the problem scenario for our app.
> Add problem scenario markdown file

- team/user_journey.md
Add the `user-journey.md` file describing our envisioned user journey and features for the app.
> Add user journey markdown file

- team/hello_worlds.md
Add the links to the Hello World repos/deployments for the rest of the team (Chris already added his in PR #13).
> rt - Add archive of Hello World apps for team

- client/src/components/list/UserList.tsx
> For simple table and button in Userlist(because no connect with backend yet)

- client/src/components/Header.tsx
- client/src/components/forms/SearchForm.tsx
- client/src/components/list/SearchList.tsx
- client/src/pages/search.tsx
- client/src/utils/createApolloAnilist.ts
Closes #34 
- Add Anilist apollo client
- Implement search anime query, component, and page
- Add search button to header
- We tested our changes locally
> Anime search using anilist

- server/src/main/java/com/github/animelist/animelist/entity/User.java
- server/src/main/java/com/github/animelist/animelist/model/user/UserListEntry.java
- server/src/main/java/com/github/animelist/animelist/model/userlist/UserList.java
- server/src/main/java/com/github/animelist/animelist/model/userlist/UserListItem.java
- server/src/main/java/com/github/animelist/animelist/model/userlist/UserListRating.java
- server/src/main/java/com/github/animelist/animelist/model/userlist/UserListSubRating.java
- server/src/main/java/com/github/animelist/animelist/model/userlist/WatchStatus.java
- server/src/main/java/com/github/animelist/animelist/service/UserListService.java
- server/src/main/java/com/github/animelist/animelist/util/MongoUtil.java
- server/src/test/java/com/github/animelist/animelist/service/UserListServiceTest.java
- Implemented UserList data structures
- Implemented UserListService create, updateItem, addItem methods (delete will be implemented later)
- Defer removing the embedded UserList implementation to #84. Instead deprecated the methods and UserListEntry class
- Manually tested the UserListService
- Unit tests
Closes #78
> Create UserList data structure and UserListService methods

- server/src/main/java/com/github/animelist/animelist/controller/UserListController.java
- server/src/main/java/com/github/animelist/animelist/model/ratingsystem/ContinuousRatingSystem.java
- server/src/main/java/com/github/animelist/animelist/model/ratingsystem/DiscreteRatingSystem.java
- server/src/main/java/com/github/animelist/animelist/model/ratingsystem/RatingSystem.java
- server/src/main/java/com/github/animelist/animelist/model/userlist/UserListRating.java
- server/src/main/java/com/github/animelist/animelist/model/userlist/UserListSubRating.java
- server/src/main/java/com/github/animelist/animelist/service/UserListService.java
- server/src/main/resources/graphql/userListSchema.graphqls
- server/src/test/java/com/github/animelist/animelist/controller/UserListControllerTest.java
- server/src/test/java/com/github/animelist/animelist/model/ratingsystem/ContinuousRatingSystemTest.java
- server/src/test/java/com/github/animelist/animelist/model/ratingsystem/DiscreteRatingSystemTest.java
- server/src/test/java/com/github/animelist/animelist/service/UserListServiceTest.java
- With a chosen size the available range of internal score values will be (0, size - 1) (inclusive)
- So ten point systems will include a "0" value so the size has been changed to 11 and offset to 0 for more natural meaning (0/10 means 0% 1/10 means 10%, 2/10 means 20% etc.)
- Internal scores are now double including subratings (Float in graphql)
- Conversion algorithm form rating system a to rating system b: first calculates the percentage ranking of the previous score calculated from the previous rating system, a, and converts by simply multiply the percentage to the maximum of internal score of rating system, b, assigns the same score across all subratings and simply calls the scoring algorithm. Mathematically, if all subratings scores are the same, then the overall score will be the …
> Rating System Scoring Algorithm

- team/MANUAL.md
Create an initial version of our manual document, meeting the lab07 requirements.
> add draft manual document

- server/src/main/java/com/github/animelist/animelist/entity/User.java
- server/src/main/java/com/github/animelist/animelist/model/userlist/EmbeddedUserList.java
- server/src/main/java/com/github/animelist/animelist/service/UserListService.java
- server/src/main/resources/graphql/schema.graphqls
- server/src/main/resources/graphql/userListSchema.graphqls
- server/src/test/java/com/github/animelist/animelist/service/UserListServiceTest.java
- In User document change userLists to be a list of embedded User list objects with the id and name. Hybrid approach by having both normalized userlists but also embedded denormalized with selected fields for faster querying
- When a user creates a userlist the user document is updated as well
- Unit tests
- Manually tested and changes are reflected
Closes #125
> jv - embed user lists in user document

- server/src/main/java/com/github/animelist/animelist/entity/User.java
- server/src/main/java/com/github/animelist/animelist/model/ratingsystem/ContinuousRatingSystem.java
- server/src/main/java/com/github/animelist/animelist/model/ratingsystem/DiscreteRatingSystem.java
- server/src/main/java/com/github/animelist/animelist/model/ratingsystem/EmbeddedRatingSystem.java
- server/src/main/java/com/github/animelist/animelist/model/ratingsystem/SubRating.java
- server/src/main/java/com/github/animelist/animelist/service/RatingSystemService.java
- server/src/main/resources/graphql/ratingSystemSchema.graphqls
- server/src/main/resources/graphql/schema.graphqls
- server/src/test/java/com/github/animelist/animelist/controller/RatingSystemControllerTest.java
- server/src/test/java/com/github/animelist/animelist/model/ratingsystem/ContinuousRatingSystemTest.java
- server/src/test/java/com/github/animelist/animelist/model/ratingsystem/DiscreteRatingSystemTest.java
- server/src/test/java/com/github/animelist/animelist/service/RatingSystemServiceTest.java
- server/src/test/java/com/github/animelist/animelist/service/UserListServiceTest.java
**REVIEW AND MERGE AFTER REVIEWING AND MERGING #131**
- Create EmbeddedRatingSystem object
- User document now has a list of embedded rating system objects to keep track of user's owned rating systems (Hybrid normalization and denormalization)
- Fixed typo in DiscreteRatingSystem subRating -> subRatings for Spring Mongo to inject fields correctly
- Fixed a bug between java float and double and graphql Float. Graphql floats are Double so we should be using Double for the weight in Subratings
- Unit tests
- Manual test
Closes #129
> jv - embed rating systems in user document

- client/src/components/list/ChooseRatingModal.tsx
- client/src/components/list/ChooseRatingModalForm.tsx
- client/src/components/list/CreateUserList.tsx
- client/src/pages/createlist.tsx
- client/src/pages/profile.tsx
Made the UI for when a user wants to create a new list.
-Values are not saved for now, but once it is connected to the backend, values should be saved,
-Also, the modal might not be needed, but I was thinking that maybe we can add info about the rating system selected on the modal on another issue
Closes #124
> ah - made the UI to create a list

- client/src/components/list/CreateUserList.tsx
- client/src/generated/graphql.tsx
- client/src/graphql/mutations/_createUserList.graphql
- client/src/graphql/queries/me.graphql
- server/src/main/java/com/github/animelist/animelist/controller/UserListController.java
- server/src/main/java/com/github/animelist/animelist/model/input/CreateUserListInput.java
- server/src/main/java/com/github/animelist/animelist/model/ratingsystem/ContinuousRatingSystem.java
- server/src/main/java/com/github/animelist/animelist/model/ratingsystem/DiscreteRatingSystem.java
- server/src/main/java/com/github/animelist/animelist/model/ratingsystem/RatingSystem.java
- server/src/main/java/com/github/animelist/animelist/service/RatingSystemService.java
- server/src/main/java/com/github/animelist/animelist/service/UserListService.java
- server/src/main/resources/graphql/userListSchema.graphqls
- server/src/test/java/com/github/animelist/animelist/controller/UserListControllerTest.java
- server/src/test/java/com/github/animelist/animelist/model/ratingsystem/ContinuousRatingSystemTest.java
- server/src/test/java/com/github/animelist/animelist/model/ratingsystem/DiscreteRatingSystemTest.java
- server/src/test/java/com/github/animelist/animelist/service/UserListServiceTest.java
- Created Default rating systems: 10 point decimal, 100 point decimal, 10 point discrete, Five stars, three smiley emojis
- Create List UI now works
- Lists the user's rating systems in dropdown menu along with the default rating menus
- Unit tests
- Manual test
Closes #137
> Create User List UI functionality

- client/src/components/list/_UserList.tsx
- Whenever the add anime modal closes we just refetch the userlist query 
- Whenever fecthing the new page we have to not include duplicates whenever concatting the list items
- **Need to update the MAX_PAGE as well** I don't think the MAX_PAGE will update properly for the case if we add anime that causes a new page to be made. So then the userlist wont go to the next page and display newly added anime. this can be done in separate issue later on.
- Manual testing. The list updates correctly if we have multiple pages or one page
Closes #141
> jv - update list when done adding anime

- server/src/main/java/com/github/animelist/animelist/controller/UserListController.java
- server/src/main/java/com/github/animelist/animelist/model/userlist/UserList.java
- server/src/main/java/com/github/animelist/animelist/service/UserListService.java
- Applied nonincreasing (high to low) sorting on backend side
- Null ratings are always less than non null ratings
- Tested manually thru UI
Closes #147
> jv - add default non increasing sort by rating

- client/src/components/profiles/AddBlockModal.tsx
- client/src/components/profiles/AddBlockOption.tsx
- client/src/components/profiles/ProfilePageBlockGrid.tsx
- client/src/components/profiles/TextBlockDisplay.tsx
- client/src/components/profiles/TextBlockModalForm.tsx
- client/src/components/profiles/UserListBlockModalForm.tsx
- client/src/generated/graphql.tsx
- client/src/graphql/mutations/updateProfilePageBlocks.graphql
- client/src/graphql/queries/profile.graphql
- client/src/pages/profile.tsx
- client/src/utils/convertBlock.tsx
- server/src/main/java/com/github/animelist/animelist/controller/ProfilePageController.java
- server/src/main/java/com/github/animelist/animelist/controller/UserController.java
- server/src/main/java/com/github/animelist/animelist/service/ProfilePageService.java
- server/src/main/resources/graphql/schema.graphqls
Closes #112.
Lengthy PR so please see video for feature demonstration:
https://user-images.githubusercontent.com/3297639/144691856-f09ce0d1-3444-4c3e-83b7-7ade2d202723.mp4
> rt - UI to add profile blocks

- client/src/components/Header.tsx
> rt - remove link to chakra docs from header

- client/src/components/list/_UserList.tsx
- client/src/generated/graphql.tsx
- client/src/graphql/mutations/updateUserList.graphql
- When user clicks on List Settings a modal pops up to update the UserList settings
- Able to update the name
- Able to update the rating system
https://user-images.githubusercontent.com/59790644/144687466-3d317a91-b35b-4868-b1e9-56df76771921.mp4
em
> Edit userlist

- client/src/generated/graphql.tsx
- client/src/graphql/queries/profile.graphql
- client/src/pages/profile/[userId].tsx
- Currently profile pages are only viewable if logged in
- users can share their profile to users and anonymous users can view thei profiles if they do not have an account
- Manual testing
#156
> jv - fix profile page accessed anonymously
